#!/bin/bash
# Written by Paul McCarty <paulm@securestack.com.au> #

stop () {
	/var/ossec/bin/ossec-control stop
	# Daemons to manage go here #
	daemons=(
		wazuh-manager
		fail2ban
        	filebeat
        	metricbeat
		logstash
		kibana
		elasticsearch
		maldet
                clamd@scan
                wazuh-api
	)

	for i in "${daemons[@]}"
	do
        	rpm -qa | grep -q $i && echo "Disabling $i" && systemctl stop $i && systemctl disable $i
	done
	rpm -qa | grep -q clamav-scanner && echo "Disabling clamd@scan" && systemctl stop clamd@scan && systemctl disable clamd@scan
}

start () {
        /var/ossec/bin/ossec-control start
        # Daemons to manage go here #
        daemons=(
                wazuh-manager
		fail2ban
                elasticsearch
                filebeat
                metricbeat
                logstash
                kibana
                #maldet
                #clamd@scan
                wazuh-api
        )

        for i in "${daemons[@]}"
        do
                rpm -qa | grep -q $i && echo "Enabling $i" && systemctl start $i && systemctl enable $i
        done
        #rpm -qa | grep -q clamav-scanner && echo "Enabling clamd@scan" && systemctl start clamd@scan && systemctl enable clamd@scan
}

configure () {
        echo "Define your local subnet here: "; read local_net
	ufw allow proto tcp from $local_net to any port 1514
	ufw allow proto tcp from $local_net to any port 1515
        echo "Define your whitelist ips here= "; read -a white_list
	for ip in ${white_list[@]}
	do
  		ufw allow proto tcp from $ip to any port 22
  		ufw allow proto tcp from $ip to any port 5601
	done

	while true; do
    		read -p "Do you want to enable clamav anti-virus? Default is no. [y/n] : " yn
    		case $yn in
        		[Yy]* ) echo "Enabling clamav..."; sed -i "s/clamav:.*/clamav: '"enabled"'/g" $home/securestack.yml; systemctl start clamd@scan; systemctl enable clamd@scan; break;;
        		[Nn]* ) echo "Disabling clamav..."; sed -i "s/clamav:.*/clamav: '"disabled"'/g" $home/securestack.yml; systemctl stop clamd@scan; systemctl disable clamd@scan; break;;
        		* ) echo "Please answer y or n.";;
    		esac
	done

        while true; do
                read -p "Do you want to enable Linux Malware Detect (LMD/maldet)? Default is no. [y/n] : " yn
                case $yn in
                        [Yy]* ) echo "Enabling maldet..."; sed -i "s/maldet:.*/maldet: '"enabled"'/g" $home/securestack.yml; systemctl start maldet; systemctl enable maldet; break;;
                        [Nn]* ) echo "Disabling maldet..."; sed -i "s/maldet:.*/maldet: '"disabled"'/g" $home/securestack.yml; systemctl stop maldet; systemctl disable maldet; break;;
                        * ) echo "Please answer y or n.";;
                esac
        done

        while true; do
                read -p "Do you want to enable fail2ban? Default is no. [y/n] : " yn
                case $yn in
                        [Yy]* ) echo "Enabling fail2ban..."; sed -i "s/fail2ban:.*/fail2ban: '"enabled"'/g" $home/securestack.yml; systemctl start fail2ban; systemctl enable fail2ban; break;;
                        [Nn]* ) echo "Disabling fail2ban..."; sed -i "s/fail2ban:.*/fail2ban: '"disabled"'/g" $home/securestack.yml; systemctl stop fail2ban; systemctl disable fail2ban; break;;
                        * ) echo "Please answer y or n.";;
                esac
        done

        while true; do
                read -p "Do you want to enable Metricbeat? Default is no. [y/n] : " yn
                case $yn in
                        [Yy]* ) echo "Enabling Metricbeat..."; sed -i "s/metricbeat:.*/metricbeat: '"enabled"'/g" $home/securestack.yml; systemctl start metricbeat; systemctl enable metricbeat; break;;
                        [Nn]* ) echo "Disabling Metricbeat..."; sed -i "s/metricbeat:.*/metricbeat: '"disabled"'/g" $home/securestack.yml; systemctl stop metricbeat; systemctl disable metricbeat; break;;
                        * ) echo "Please answer y or n.";;
                esac
        done

        while true; do
                read -p "Do you want to enable Filebeat? Default is no. [y/n] : " yn
                case $yn in
                        [Yy]* ) echo "Enabling Filebeat..."; sed -i "s/filebeat:.*/filebeat: '"enabled"'/g" $home/securestack.yml; systemctl start filebeat; systemctl enable filebeat; break;;
                        [Nn]* ) echo "Disabling Filebeat..."; sed -i "s/filebeat:.*/filebeat: '"disabled"'/g" $home/securestack.yml; systemctl stop filebeat; systemctl disable filebeat; break;;
                        * ) echo "Please answer y or n.";;
                esac
        done


	#echo "Do you want to enable Web Application Firewall? y/n Default is no. "; read waf_ans
	#echo "Do you want to harden this linux operating system? y/n Default is yes. "; read harden_ans
}

# Variables go here #
home=/opt/securestack/

case "$1" in

help)  help
    ;;
stop)  stop
    ;;
start)  start
    ;;
configure)  configure
    ;;
status)  status $@
    ;;
*)  echo "SecureStack copyright 2017 - Paul McCarty"
    echo "Usage: securestack (configure|stop|start|role)    "
    echo " "
    exit 1
   ;;
esac

