#!/bin/bash
# Written by Paul McCarty <paulm@securestack.com.au> #

stop () {
	sudo /var/ossec/bin/ossec-control stop
	# Daemons to manage go here #
	daemons=(
		wazuh-manager
		fail2ban
        	filebeat
        	metricbeat
		logstash
		kibana
		elasticsearch
		maldet
                clamd@scan
                wazuh-api
	)

	for i in "${daemons[@]}"
	do
        	sudo rpm -qa | grep -q $i && echo "Disabling $i" && sudo systemctl stop $i && sudo systemctl disable $i
	done
	sudo rpm -qa | grep -q clamav-scanner && echo "Disabling clamd@scan" && sudo systemctl stop clamd@scan && sudo systemctl disable clamd@scan
}

start () {
        sudo /var/ossec/bin/ossec-control start
	sudo systemctl enable wazuh-manager
	sudo systemctl start wazuh-manager
        # Daemons to manage go here #
        daemons=(
		fail2ban
                elasticsearch
                filebeat
                metricbeat
                logstash
                kibana
                #maldet
                #clamd@scan
                wazuh-api
        )

        for i in "${daemons[@]}"
        do
                sudo rpm -qa | grep -q $i && echo "Enabling $i" && sudo systemctl start $i && sudo systemctl enable $i
        done
        #rpm -qa | grep -q clamav-scanner && echo "Enabling clamd@scan" && sudo systemctl start clamd@scan && sudo systemctl enable clamd@scan
}

configure () {
	echo "############ local_net section #######################################"
        echo "What subnets do you want to have access to this SecureStack server?"
	echo "If you are deploying to AWS this is usually the main IPv4 CIDR block attached to your VPC"
	echo "or you can specify individual subnets but this will limit what instances can talk to this"
	echo "SecureStack server."
        echo "Please include all networks that will be managed by this particular instance of SecureStack."
	echo "Enter subnets here:  "; read -a local_net
        for subnets in ${local_net[@]}
        do
                sudo ufw allow proto tcp from $local_net to any port 1514
        	sudo ufw allow proto tcp from $local_net to any port 1515 
        done

	echo "############ white_list section ######################################"
	echo "This is where you define what IP addresses or networks you want to have administrative"
	echo "access to this SecureStack server.  This access is limited to tcp 5601 for Kibana and"
	echo "tcp 22 for ssh.  Please be careful as you can lock yourself out of your server if you"
	echo "enter the wrong values here.  You can cancel by hitting Ctrl-C now which will leave ssh"
	echo "open but you won't be able to use the web UI until you define this access."
	echo "---- Hit Ctrl-C now to exit or any key to continue -------------------"; read 
        echo "Define your whitelist ips here: "; read -a white_list
	echo "Deleting existing firewall rules..."
	sudo ufw reset
	sudo ufw enable
	for ip in ${white_list[@]}
	do
  		sudo ufw allow proto tcp from $ip to any port 22
  		sudo ufw allow proto tcp from $ip to any port 5601
	done
	echo "Removing inital ssh rule..."
	sudo ufw delete 1

	while true; do
    		read -p "Do you want to enable clamav anti-virus? Default is no. [y/n] : " yn
    		case $yn in
        		[Yy]* ) echo "Enabling clamav..."; sudo sed -i "s/clamav:.*/clamav: '"enabled"'/g" $home/securestack.yml; sudo systemctl start clamd@scan; sudo systemctl enable clamd@scan; break;;
        		[Nn]* ) echo "Disabling clamav..."; sudo sed -i "s/clamav:.*/clamav: '"disabled"'/g" $home/securestack.yml; sudo systemctl stop clamd@scan; sudo systemctl disable clamd@scan; break;;
        		* ) echo "Please answer y or n.";;
    		esac
	done

        while true; do
                read -p "Do you want to enable Linux Malware Detect (LMD/maldet)? Default is no. [y/n] : " yn
                case $yn in
                        [Yy]* ) echo "Enabling maldet..."; sudo sed -i "s/maldet:.*/maldet: '"enabled"'/g" $home/securestack.yml; sudo systemctl start maldet; sudo systemctl enable maldet; break;;
                        [Nn]* ) echo "Disabling maldet..."; sudo sed -i "s/maldet:.*/maldet: '"disabled"'/g" $home/securestack.yml; sudo systemctl stop maldet; sudo systemctl disable maldet; break;;
                        * ) echo "Please answer y or n.";;
                esac
        done

        while true; do
                read -p "Do you want to enable fail2ban? Default is no. [y/n] : " yn
                case $yn in
                        [Yy]* ) echo "Enabling fail2ban..."; sudo sed -i "s/fail2ban:.*/fail2ban: '"enabled"'/g" $home/securestack.yml; sudo systemctl start fail2ban; sudo systemctl enable fail2ban; break;;
                        [Nn]* ) echo "Disabling fail2ban..."; sudo sed -i "s/fail2ban:.*/fail2ban: '"disabled"'/g" $home/securestack.yml; sudo systemctl stop fail2ban; sudo systemctl disable fail2ban; break;;
                        * ) echo "Please answer y or n.";;
                esac
        done

        while true; do
                read -p "Do you want to enable Metricbeat? Default is no. [y/n] : " yn
                case $yn in
                        [Yy]* ) echo "Enabling Metricbeat..."; sudo sed -i "s/metricbeat:.*/metricbeat: '"enabled"'/g" $home/securestack.yml; sudo systemctl start metricbeat; sudo systemctl enable metricbeat; break;;
                        [Nn]* ) echo "Disabling Metricbeat..."; sudo sed -i "s/metricbeat:.*/metricbeat: '"disabled"'/g" $home/securestack.yml; sudo systemctl stop metricbeat; sudo systemctl disable metricbeat; break;;
                        * ) echo "Please answer y or n.";;
                esac
        done

        while true; do
                read -p "Do you want to enable Filebeat? Default is no. [y/n] : " yn
                case $yn in
                        [Yy]* ) echo "Enabling Filebeat..."; sudo sed -i "s/filebeat:.*/filebeat: '"enabled"'/g" $home/securestack.yml; sudo systemctl start filebeat; sudo systemctl enable filebeat; break;;
                        [Nn]* ) echo "Disabling Filebeat..."; sudo sed -i "s/filebeat:.*/filebeat: '"disabled"'/g" $home/securestack.yml; sudo systemctl stop filebeat; sudo systemctl disable filebeat; break;;
                        * ) echo "Please answer y or n.";;
                esac
        done


	#echo "Do you want to enable Web Application Firewall? y/n Default is no. "; read waf_ans
	#echo "Do you want to harden this linux operating system? y/n Default is yes. "; read harden_ans
}

update () {
	cd /opt/securestack && git pull
}

# Variables go here #
home=/opt/securestack/

case "$1" in

help)  help
    ;;
stop)  stop
    ;;
start)  start
    ;;
configure)  configure
    ;;
status)  status $@
    ;;
*)  echo "SecureStack copyright 2017 - Paul McCarty"
    echo "Usage: securestack (configure|stop|start|role)    "
    echo " "
    exit 1
   ;;
esac

